language: python

python:
  - '2.7'
  #- '3.2'

virtualenv:
  system_site_packages: true

# Install as many packages as possible via pip, but some require apt-get.
before_install:
  - sudo apt-get update
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get install python-scipy python-qt4; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then sudo apt-get install python3-scipy python3-pyqt4; fi
  - pip install matplotlib pandas control six

install:
  - python setup.py install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - python -m doctest tests/tests.txt
  # - bash runtests.sh # Not yet ready to run all tests in Travis
