language: c
# By setting the language to c instead of python, it's possible to use apt-get.
# It's difficult to get the scipy stack installed via pip.

python:
  - 2.6
  - 2.7

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - sudo apt-get -q install python-numpy python-scipy python-matplotlib ipython python-pandas libwxgtk2.8-0 python-wxtools python-easygui python-qt4
  - sudo pip install control

install: 
  - python setup.py build && sudo python setup.py install

script: 
  - bash 00-test.sh
