language: python

python:
  - 2.7

install: 
  - sudo apt-get update && sudo apt-get install python-numpy 
  - sudo apt-get install python-scipy 
  - sudo apt-get install python-matplotlib
  - sudo apt-get install ipython 
  - sudo apt-get install python-pandas 
  - sudo apt-get install python-wxgtk2.8
  - sudo apt-get install python-easygui
  - sudo apt-get install python-pip
  - pip install control
  - python setup.py build && sudo python setup.py install

script: 
  - bash 00-test.sh
